### ISSUE TITLE
Error during gulp setup

### ISSUE THREAD

**Issue by ghost** [million12/M12.FoundationSite#2]
Hello,

I'm trying to install the M12.FoundationSite on an debian jessie based VM. I developed an site with that extention last year using neos-2.0 whom i try to update now.
I start with an plain neos installation with the two packages added to composer.json. npm install and bower install pass without issues.
Running gulp setup fails with 

```
.then(()=>{

SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9
```

I changed the line 64 in gulpfile.js into

`.then( function () {`

Now gulp setup fails with 

```
[19:02:33] Using gulpfile /var/www/Neos-2.1/Packages/Sites/M12.FoundationSite/gulpfile.js
[19:02:33] Starting 'assets'...
[19:02:33] Finished 'assets' after 4.29 ms
[19:02:33] Starting 'styles'...
[19:02:35] Finished 'styles' after 1.65 s
[19:02:35] Starting 'scripts-hinting'...
[19:02:35] Starting 'scripts'...
[19:02:36] Finished 'scripts-hinting' after 1.09 s
[19:02:36] App.js 545.33 kB

zlib.js:166
    callback(null, buf);
    ^
TypeError: object is not a function
    at Gzip.onEnd (zlib.js:166:5)
    at Gzip.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

```

At that point I'm abit lost.

**Comment by sryzycki** [comment]
Hello,
Could you paste in the exact command that you run before you get these errors? Thanks

**Comment by ghost** [comment]
Of course.

I start with an neos installation
`./composer.phar create-project typo3/neos-base-distribution Neos-2.1`

I add the following to compser.json 

```
"require": {
       ....
       "m12/neos-foundation": "dev-master",
        "m12/neos-foundation-site": "dev-master"
} 
```

and i remove the demosite package.
Afterwards I run

```
cd Neos-2.1
../composer.phar update
cd Packages/Sites/M12.FoundationSite
npm install
bower --allow-root install
gulp build

```

The last command results in

```
/var/www/Neos-2.1/Packages/Sites/M12.FoundationSite/gulpfile.js:64
                .then(() => {
                       ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)

```

I use 
nodejs (v0.12.12)
npm (2.14.9)
bower (1.7.7)

**Comment by ghost** [comment]
Hmm I updated nodejs from 0.10 to 0.12 and with that version and the modification to gulpfile.js from my first post. gulp build now works. Had overseen the warning during npm install.

**Comment by ghost** [comment]
Well the issue was closed but the construct in line 64 of gulpfile.js is still causing an error with gulp setup if it is left like that.

**Comment by ryzy** [comment]
Did you manage to resolve the issue, @achim71? It seems like it's just incompatibility of npm versions. Now you can use this package with NVM and currently it works perfectly fine with Node 6.3.0.

Would like to close this one...

**Comment by ghost** [comment]
Hmm, been a while it worked with an newer npm version here i think.

Am 04.08.2016 um 14:24 schrieb Marcin Ryzycki:
